# Generated by Django 4.2.4 on 2023-11-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectID', models.CharField(max_length=255)),
                ('subjectName', models.CharField(max_length=255)),
                ('numOfStudents', models.IntegerField()),
            ],
            options={
                'ordering': ('subjectID',),
            },
        ),
    ]
