# Generated by Django 4.2.4 on 2023-11-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject_name', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('num_of_students', models.IntegerField()),
            ],
        ),
    ]
