# Generated by Django 4.2.4 on 2023-11-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_examarrangement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examarrangement',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='examarrangement',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
