# Generated by Django 4.2.4 on 2023-12-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_examarrangement_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField()),
            ],
        ),
    ]
